"""Everything in this service talks to models through LocalLLM — one
interface, three backends.

MockBackend: fake, instant, zero downloads. Answers are templated so it's
dumb as rocks, but that's fine — it's just here so you can build the API,
prompts, retries and benchmarks against something.

HFBackend: a real Hugging Face model. Needs torch + transformers +
accelerate, and honestly a GPU for anything above ~3B.

VLLMBackend: the same model served by vLLM — paged attention +
continuous batching, so much higher tok/s on a GPU. Needs the vllm
package and CUDA; falls back to HFBackend with a warning without it.

Swap between them with one line in config.yaml:  backend: mock -> hf -> vllm

APIBackend: a real model over a free HTTPS API (Gemini / OpenRouter) via
llm_client.py — no SDK, no weights, works on Render's free tier. Selected
with backend: api, or automatically when LLM_API_KEY is set (LLM_AUTO=0
disables the auto-select). Falls back to the mock with a note when the
call fails.

Startup: backends load lazily by default (the first request pays the load
cost). Set lazy_load: false in config.yaml to warm the model up at startup
instead — slower boot, fast first request.
"""
import json
import os
import random
import sys
import threading
import time
import re

import yaml

try:
    import jsonschema
except ImportError:
    # extract_json raises loudly if you ask for schema validation without
    # this — never silently return unvalidated JSON
    jsonschema = None


def _violation_text(errors):
    # keep the retry prompt short — the model only needs the highlights
    bits = []
    for e in errors[:3]:
        where = ".".join(str(p) for p in e.absolute_path) or "root"
        bits.append(f"{where}: {e.message}")
    if len(errors) > 3:
        bits.append(f"+{len(errors) - 3} more")
    return "; ".join(bits)


# ---------------------------------------------------------------- backends
class MockBackend:
    """Not a real model — templated answers, runs instantly. Good enough
    to build everything else against."""

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        if "JSON" in prompt:
            # echo the requested fields back with mock values, so the
            # extraction retry-loop has something valid to validate
            m = re.search(r"fields: ([^\n.]+)", prompt)
            if m:
                fields = [f.strip() for f in m.group(1).split(",")
                          if f.strip()]
                return json.dumps({f: "mock-" + f for f in fields})
            return '{"order_id": "ORD-1", "items": 2}'
        return ("This is a mock completion. In production this text would be "
                "generated by the loaded model.")

    def warmup(self):
        # nothing to warm — templated answers, zero load cost
        pass

    def stream(self, prompt, max_new_tokens=256):
        for word in self.generate(prompt, max_new_tokens).split():
            time.sleep(0.005)
            yield word + " "


class HFBackend:
    """The real thing. pip install torch transformers accelerate first,
    and honestly a GPU for anything above ~3B.

    Loads lazily on the first generate call unless config sets
    lazy_load: false — so importing app.py with backend: hf stays cheap
    until the model is actually needed.

    quantization: "none" (default) or "8bit". 8-bit loads the weights
    as int8 via bitsandbytes (works on CPU too, dequantizes on the fly
    at each matmul). Set in config.yaml; falls back to "none" with a
    warning if the 8-bit load fails for any reason.
    """

    # vram maths for Qwen2-0.5B-Instruct, worked out before loading:
    #   weights:    494M params x 2 B (fp16)            ~ 1.0 GB
    #   kv cache:   2 x 24 layers x 896 dim x 2 B       ~ 86 KB per token
    #               (2k-ctx worst case -> ~170 MB, usually way less)
    #   torch + activations overhead                    ~ 300 MB
    #   peak total                                      ~ 1.5 GB
    # so ~2 GB of free VRAM (or RAM on CPU) is the honest minimum.
    # on CPU the same maths applies in RAM, just ~10x slower per token.
    # with quantization: 8bit the weights halve to ~0.5 GB (CPU int8 path).

    def __init__(self, model_id, dtype="float16", quantization="none"):
        self.model_id = model_id
        self.dtype = dtype
        q = str(quantization or "none").lower()
        self.quantization = q if q in ("none", "8bit") else "none"
        self.torch = None   # set by _ensure_loaded, kept for dtype lookups
        self.tok = None
        self.model = None

    @property
    def loaded(self):
        return self.model is not None

    def _ensure_loaded(self):
        if self.loaded:
            return
        try:
            import torch
        except ImportError as e:
            raise RuntimeError(
                "HF backend needs torch (pip install torch) — or flip "
                "config.yaml back to backend: mock") from e
        try:
            from transformers import AutoTokenizer, AutoModelForCausalLM
        except ImportError as e:
            raise RuntimeError(
                "HF backend needs transformers (pip install transformers "
                "accelerate)") from e
        # fp16 matmuls are a GPU thing — on CPU float32 is faster and safer
        dtype = (torch.float32 if not torch.cuda.is_available()
                 else getattr(torch, self.dtype, torch.float16))
        try:
            tok = AutoTokenizer.from_pretrained(self.model_id)
            if self.quantization == "8bit":
                try:
                    model = self._load_8bit()
                except Exception as e:
                    # 8-bit didn't pan out — warn loudly, serve unquantized
                    print(f"warning: 8-bit quantization failed ({e}); "
                          "falling back to unquantized weights")
                    self.quantization = "none"
                    model = self._load_plain(dtype)
            else:
                model = self._load_plain(dtype)
        except Exception as e:
            raise RuntimeError(
                f"couldn't fetch {self.model_id} from the HF hub "
                f"(check the model id and your network): {e}") from e
        self.torch, self.tok, self.model = torch, tok, model

    def _load_plain(self, dtype):
        from transformers import AutoModelForCausalLM
        return AutoModelForCausalLM.from_pretrained(
            self.model_id, dtype=dtype, device_map="auto")

    def _load_8bit(self):        # bitsandbytes keeps weights as int8 + an fp scale per row and
        # dequantizes on the fly at each matmul — real halved memory,
        # slight speed cost, works on CPU (no CUDA kernel needed for this)
        from transformers import AutoModelForCausalLM, BitsAndBytesConfig
        return AutoModelForCausalLM.from_pretrained(
            self.model_id,
            quantization_config=BitsAndBytesConfig(load_in_8bit=True),
            device_map="auto")

    def warmup(self):
        # pay the load cost now, not on the first request; one tiny
        # generate past _ensure_loaded shakes down kernels / kv cache
        self._ensure_loaded()
        self.generate("warmup", max_new_tokens=1, temperature=0)

    @property
    def tokenizer(self):
        # chat template needs the tokenizer even before the first generate
        self._ensure_loaded()
        return self.tok

    def _inputs(self, prompt):
        self._ensure_loaded()
        return self.tok(prompt, return_tensors="pt").to(self.model.device)

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        self._ensure_loaded()
        inputs = self._inputs(prompt)
        out = self.model.generate(**inputs, max_new_tokens=max_new_tokens,
                                  temperature=temperature,
                                  do_sample=temperature > 0)  # greedy when 0
        return self.tok.decode(out[0][inputs.input_ids.shape[1]:],
                               skip_special_tokens=True)

    def stream(self, prompt, max_new_tokens=256):
        from transformers import TextIteratorStreamer
        from threading import Thread
        self._ensure_loaded()
        inputs = self._inputs(prompt)
        streamer = TextIteratorStreamer(self.tok, skip_special_tokens=True,
                                        skip_prompt=True)  # prompt would echo otherwise
        Thread(target=self.model.generate,
               kwargs={**inputs, "max_new_tokens": max_new_tokens,
                       "streamer": streamer}, daemon=True).start()
        yield from streamer


class VLLMBackend:
    """Same generate/stream interface, but served by vLLM — paged
    attention + continuous batching, so much higher tok/s on a GPU.

    Needs: pip install vllm, and a CUDA GPU (vLLM doesn't do CPU).
    Loads lazily on the first generate call unless config sets
    lazy_load: false. If the vllm package isn't importable, __init__
    raises and LocalLLM falls back to the HF backend with a warning —
    same model, just slower.
    """

    def __init__(self, model_id, quantization="none"):
        try:
            import vllm  # noqa: F401 — availability probe, real import is lazy
        except ImportError as e:
            raise RuntimeError(
                "vllm backend needs the vllm package "
                "(pip install vllm, CUDA GPU required)") from e
        self.model_id = model_id
        q = str(quantization or "none").lower()
        self.quantization = q if q in ("none", "awq", "gptq") else "none"
        self.llm = None

    @property
    def loaded(self):
        return self.llm is not None

    def _ensure_loaded(self):
        if self.loaded:
            return
        from vllm import LLM
        # vllm grabs ~90% of GPU RAM by default; fine on a dedicated box,
        # lower gpu_memory_utilization if you're sharing it
        self.llm = LLM(
            model=self.model_id,
            quantization=(self.quantization
                          if self.quantization != "none" else None))

    def warmup(self):
        # same deal as the HF backend: load now, one dummy token shakes
        # down the engine before real traffic arrives
        self._ensure_loaded()
        self.generate("warmup", max_new_tokens=1, temperature=0)

    @property
    def tokenizer(self):
        # chat template needs the tokenizer even before the first generate
        self._ensure_loaded()
        return self.llm.get_tokenizer()

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        from vllm import SamplingParams
        self._ensure_loaded()
        params = SamplingParams(max_tokens=max_new_tokens,
                                temperature=temperature)
        return self.llm.generate([prompt], params)[0].outputs[0].text

    def stream(self, prompt, max_new_tokens=256):
        # vllm's offline LLM.generate returns whole outputs — no public
        # streaming iterator — so chunk the finished text like MockBackend;
        # TTFT here ~= full generate latency, not a real first token
        for word in self.generate(prompt, max_new_tokens).split():
            yield word + " "


# ------------------------------------------------- retry + circuit breaker
class BreakerOpenError(Exception):
    # the backend is known-down, so this call failed fast instead of
    # burning retries against it. retry_after says how long to wait.
    def __init__(self, message, retry_after=0.0):
        super().__init__(message)
        self.retry_after = retry_after


class _CircuitBreaker:
    # after `failure_threshold` consecutive failures the breaker opens and
    # calls fail fast for `cooldown` seconds; then one probe goes through
    # (half-open) — success closes it, failure opens it again. only one
    # probe at a time, everyone else fails fast. thread-safe: uvicorn runs
    # the sync endpoints in a threadpool.
    def __init__(self, failure_threshold=5, cooldown_seconds=30.0,
                 enabled=True):
        self.failure_threshold = max(1, int(failure_threshold))
        self.cooldown = max(0.0, float(cooldown_seconds))
        self.enabled = enabled
        self._state = "closed"      # closed | open | half-open
        self._failures = 0          # consecutive failures while closed
        self._opened_at = 0.0
        self._probing = False
        self._lock = threading.Lock()

    def _enter(self):
        # call before every attempt — raises BreakerOpenError when the
        # call must fail fast instead of touching the backend
        with self._lock:
            if not self.enabled or self._state == "closed":
                return
            if self._state == "open":
                if time.monotonic() - self._opened_at >= self.cooldown:
                    self._state = "half-open"  # fall through: this call probes
                else:
                    wait = self.cooldown - (time.monotonic() - self._opened_at)
                    raise BreakerOpenError(
                        "backend circuit breaker is open — the model "
                        "backend looks down, failing fast",
                        retry_after=max(0.0, wait))
            if self._state == "half-open":
                if self._probing:
                    raise BreakerOpenError(
                        "backend circuit breaker is open — recovery probe "
                        "already in flight", retry_after=self.cooldown)
                self._probing = True

    def _success(self):
        with self._lock:
            self._failures = 0
            self._state = "closed"
            self._probing = False

    def _failure(self):
        with self._lock:
            self._failures += 1
            self._probing = False
            if self._state == "half-open" or \
                    self._failures >= self.failure_threshold:
                self._state = "open"
                self._opened_at = time.monotonic()

    def status(self):
        with self._lock:
            return {"enabled": self.enabled,
                    "state": self._state,
                    "consecutive_failures": self._failures}


def _env_on(name, default):
    # LLM_FOO=0/false/no/off/disabled turns it off; unset keeps the default
    v = os.environ.get(name)
    if v is None:
        return bool(default)
    return v.strip().lower() not in ("0", "false", "no", "off", "disabled")


def _env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return int(default)


def _env_float(name, default):
    try:
        return float(os.environ.get(name, default))
    except (TypeError, ValueError):
        return float(default)


# ---------------------------------------------------------------- LLM
class APIBackend:
    """Real model over a free API (Gemini / OpenRouter) via llm_client.

    No SDK, no weights — just HTTPS, so it runs fine on Render's free
    tier. generate() falls back to the mock (with a visible note) when
    the call fails, so the service never breaks for demo traffic."""

    def __init__(self):
        from llm_client import FreeLLMClient
        self.client = FreeLLMClient.from_env()
        if self.client is None:
            raise RuntimeError(
                "api backend needs LLM_API_KEY in the environment "
                "(unset key -> the mock backend stays the default)")
        self._mock = MockBackend()
        self.last_error = None  # last api failure, if any — surfaced on /info

    @property
    def loaded(self):
        return True  # nothing to load — it's just HTTPS

    def warmup(self):
        pass  # nothing local to warm; keep startup network-free

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        try:
            out = self.client.generate(prompt, max_tokens=max_new_tokens,
                                       temperature=temperature)
            self.last_error = None  # recovered — badge goes green again
            return out
        except Exception as e:  # llm_client only ever raises FreeLLMError
            self.last_error = str(e)  # key-free by construction — safe for /info
            print(f"api backend: model call failed ({e}) — mock instead",
                  file=sys.stderr)
            return (self._mock.generate(prompt, max_new_tokens)
                    + "\n\n[model unavailable — showing offline mock result]")

    def stream(self, prompt, max_new_tokens=256):
        # these APIs can stream, but this client keeps it simple — chunk
        # the finished text like MockBackend does
        for word in self.generate(prompt, max_new_tokens).split():
            yield word + " "


class LocalLLM:
    def __init__(self, config_path="config.yaml", quantization=None,
                 backend=None):
        self.cfg = yaml.safe_load(open(config_path))
        # explicit kwarg (bench) beats config.yaml
        which = backend or self.cfg.get("backend", "mock")
        if which == "vllm":
            try:
                self.backend = VLLMBackend(
                    self.cfg["model_id"],
                    self.cfg.get("vllm_quantization", "none"))
            except RuntimeError as e:
                # no vllm package on this box — serve the same model
                # through the HF backend instead of refusing to start
                print(f"warning: {e}; falling back to the HF backend")
                self.backend = HFBackend(self.cfg["model_id"],
                                         self.cfg.get("dtype", "float16"))
        elif which == "hf":
            # explicit kwarg (bench) beats config.yaml; default none keeps
            # yesterday's behaviour untouched
            q = (quantization if quantization is not None
                 else self.cfg.get("quantization", "none"))
            self.backend = HFBackend(self.cfg["model_id"],
                                     self.cfg.get("dtype", "float16"),
                                     quantization=q)
        elif which == "api":
            self.backend = APIBackend()
        else:
            self.backend = MockBackend()
        # retry + circuit breaker around backend calls — config.yaml sets
        # the defaults, LLM_RETRY_* / LLM_CB_* env vars override per deploy
        rc = self.cfg.get("retry") or {}
        cb = self.cfg.get("circuit_breaker") or {}
        self._retry_enabled = _env_on("LLM_RETRY_ENABLED",
                                      rc.get("enabled", True))
        self._max_attempts = max(1, _env_int("LLM_RETRY_MAX_ATTEMPTS",
                                            rc.get("max_attempts", 3)))
        self._base_delay = max(0.0, _env_float(
            "LLM_RETRY_BASE_DELAY", rc.get("base_delay_seconds", 0.5)))
        self._jitter = max(0.0, _env_float(
            "LLM_RETRY_JITTER", rc.get("jitter_seconds", 0.25)))
        self._breaker = _CircuitBreaker(
            failure_threshold=_env_int("LLM_CB_FAILURE_THRESHOLD",
                                       cb.get("failure_threshold", 5)),
            cooldown_seconds=_env_float("LLM_CB_COOLDOWN",
                                        cb.get("cooldown_seconds", 30.0)),
            enabled=_env_on("LLM_CB_ENABLED", cb.get("enabled", True)))
        # prompts live as versioned files, not inline strings — much easier
        # to diff v1 vs v2 later when something regresses
        self.prompt_dir = self.cfg.get("prompt_dir", "prompts/v1")
        # lazy_load: true (default) keeps the model loading on the first
        # request; false warms it up here so that first request is fast.
        # a failed warmup fails startup loudly — that's the point, you'd
        # rather know at deploy time than on the first real request
        if not self.cfg.get("lazy_load", True):
            self.warmup()

    def warmup(self):
        # pull the load cost into startup — also callable by hand
        # (e.g. from a readiness probe) when lazy_load stays true
        t0 = time.perf_counter()
        self.backend.warmup()
        print(f"model warmed up in {time.perf_counter() - t0:.1f}s "
              f"({type(self.backend).__name__})")

    def load_prompt(self, name, **kwargs):
        text = open(f"{self.prompt_dir}/{name}.txt").read()
        return text.format(**kwargs)

    def build_prompt(self, messages):
        # HF and vLLM expose the tokenizer's real chat template; the mock
        # gets the cheap stand-in
        if hasattr(self.backend, "tokenizer"):
            return self.backend.tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True)
        return "\n".join(f"{m['role']}: {m['content']}" for m in messages
                         ) + "\nassistant:"

    def _with_retry(self, call):
        # one backend call with retry: exponential backoff + jitter on
        # transient failures, breaker fail-fast when the backend is down
        attempts = self._max_attempts if self._retry_enabled else 1
        for attempt in range(1, attempts + 1):
            self._breaker._enter()   # raises BreakerOpenError when open
            try:
                out = call()
            except BreakerOpenError:
                raise                # fail-fast is never retried
            except Exception:
                self._breaker._failure()
                if attempt == attempts:
                    raise
                # backoff doubles each attempt; jitter desyncs the herd
                # when the backend comes back up
                time.sleep(self._base_delay * (2 ** (attempt - 1)) +
                           random.uniform(0, self._jitter))
            else:
                self._breaker._success()
                return out

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        # the resilient way to call the backend — every endpoint goes
        # through here, never llm.backend.generate directly
        return self._with_retry(
            lambda: self.backend.generate(prompt,
                                          max_new_tokens=max_new_tokens,
                                          temperature=temperature))

    def stream(self, prompt, max_new_tokens=256):
        # regular method (not a generator) so the breaker check below runs
        # eagerly — a dead backend is a clean 503 before any SSE headers,
        # not a hung stream that dies mid-flight
        self._breaker._enter()
        return self._stream_gen(prompt, max_new_tokens)

    def _stream_gen(self, prompt, max_new_tokens):
        attempts = self._max_attempts if self._retry_enabled else 1
        for attempt in range(1, attempts + 1):
            if attempt > 1:
                self._breaker._enter()  # breaker may have opened meanwhile
            try:
                yielded = False
                for chunk in self.backend.stream(prompt, max_new_tokens):
                    yielded = True
                    yield chunk
            except BreakerOpenError:
                raise
            except Exception:
                self._breaker._failure()
                # only retry a stream that died before its first chunk —
                # a half-sent reply can't be replayed cleanly
                if yielded or attempt == attempts:
                    raise
                time.sleep(self._base_delay * (2 ** (attempt - 1)) +
                           random.uniform(0, self._jitter))
            else:
                self._breaker._success()
                return

    def breaker_status(self):
        # surfaced on /info so the demo badge can show it
        return self._breaker.status()

    def chat(self, messages, max_new_tokens=256, temperature=0.7):
        return self.generate(self.build_prompt(messages),
                             max_new_tokens, temperature)

    def chat_stream(self, messages, max_new_tokens=256):
        return self.stream(self.build_prompt(messages), max_new_tokens)

    def prepare_history(self, messages, strategy=None):
        # one place the chat endpoints go through before the model sees a
        # conversation: cut the history down to the context budget. the
        # strategy comes from the call, then LLM_HISTORY_STRATEGY, then
        # config.yaml's history.strategy — default sliding_window, the one
        # that needs no model at all
        from history import truncate
        hcfg = self.cfg.get("history") or {}
        strat = (strategy or os.environ.get("LLM_HISTORY_STRATEGY")
                 or hcfg.get("strategy", "sliding_window"))
        budget = _env_int("LLM_HISTORY_MAX_TOKENS",
                          hcfg.get("max_tokens", 4096))
        keep_recent = _env_int("LLM_HISTORY_KEEP_RECENT",
                               hcfg.get("keep_recent", 10))
        return truncate(messages, strategy=strat, max_tokens=budget,
                        keep_recent=keep_recent,
                        summariser=self._summarise_older)

    def _summarise_older(self, older):
        # summarise strategy's workhorse: ask the backend for a short
        # summary of the dropped turns. mock-safe — whatever the backend
        # answers becomes the summary; if the call fails, excerpt the
        # turns instead of erroring the whole chat
        try:
            doc = "\n".join(f"{m.get('role', '')}: {m.get('content', '')}"
                            for m in older)
            prompt = self.load_prompt("summarise", max_words=150,
                                      document=doc)
            return self.generate(prompt, max_new_tokens=220,
                                 temperature=0.3).strip()
        except Exception:
            excerpt = "\n".join(
                f"{m.get('role', '')}: {m.get('content', '')}"
                for m in older[:4])
            return ("[summary unavailable — first turns of the dropped "
                    f"history]\n{excerpt}")

    # -- structured output: ask -> check what came back -> show the model
    #    its mistake and try again ----------------------------------------
    @staticmethod
    def _extract_json(text, schema):
        # cheap trick: grab the outermost { ... } instead of trusting the
        # model to output *only* JSON (it rarely does on the first try)
        start, end = text.find("{"), text.rfind("}")
        if start == -1:
            return None, "no JSON object found"
        try:
            obj = json.loads(text[start:end + 1])
        except json.JSONDecodeError as e:
            return None, f"invalid JSON: {e}"
        if jsonschema is None:
            raise RuntimeError("jsonschema is not installed — "
                               "pip install jsonschema to validate "
                               "structured output")
        try:
            validator = jsonschema.Draft202012Validator(schema)
        except jsonschema.SchemaError as e:
            # your schema is broken — a retry won't fix that, say so now
            raise ValueError("bad JSON schema passed to extract_json: "
                             f"{e.message}") from None
        errors = sorted(validator.iter_errors(obj),
                        key=lambda e: (list(e.absolute_path), e.message))
        if errors:
            return None, "schema violations: " + _violation_text(errors)
        return obj, None

    def extract_json(self, prompt, required, retries=2, schema=None):
        # naming the fields up front helps real models too — vague
        # "give me JSON" prompts come back with the wrong shape
        if schema is not None:
            # full JSON-schema validation, not just required fields —
            # violations feed back into the retry loop like anything else
            prompt += ("\nRespond with ONLY a JSON object conforming to "
                       "this JSON Schema: %s" % json.dumps(schema))
            validate_against = schema
        else:
            # no schema: keep the old suffix byte-for-byte — the prompt
            # regression goldens pin this text exactly
            prompt += ("\nRespond with ONLY a JSON object with these "
                       "fields: %s." % ", ".join(required))
            validate_against = {"type": "object", "required": list(required)}
        for _ in range(retries + 1):
            raw = self.generate(prompt)  # transient backend blips get
            # retried inside generate; this loop is only for bad JSON
            obj, err = self._extract_json(raw, validate_against)
            if obj:
                return obj
            prompt += f"\nYour last output had an error: {err}. Fix it."
        raise ValueError("model failed to produce valid JSON after retries")
