"""Everything in this service talks to models through LocalLLM — one
interface, three backends.

MockBackend: fake, instant, zero downloads. Answers are templated so it's
dumb as rocks, but that's fine — it's just here so you can build the API,
prompts, retries and benchmarks against something.

HFBackend: a real Hugging Face model. Needs torch + transformers +
accelerate, and honestly a GPU for anything above ~3B.

VLLMBackend: the same model served by vLLM — paged attention +
continuous batching, so much higher tok/s on a GPU. Needs the vllm
package and CUDA; falls back to HFBackend with a warning without it.

Swap between them with one line in config.yaml:  backend: mock -> hf -> vllm
"""
import json
import time
import re

import yaml


# ---------------------------------------------------------------- backends
class MockBackend:
    """Not a real model — templated answers, runs instantly. Good enough
    to build everything else against."""

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        if "JSON" in prompt:
            # echo the requested fields back with mock values, so the
            # extraction retry-loop has something valid to validate
            m = re.search(r"fields: ([^\n.]+)", prompt)
            if m:
                fields = [f.strip() for f in m.group(1).split(",")
                          if f.strip()]
                return json.dumps({f: "mock-" + f for f in fields})
            return '{"order_id": "ORD-1", "items": 2}'
        return ("This is a mock completion. In production this text would be "
                "generated by the loaded model.")

    def stream(self, prompt, max_new_tokens=256):
        for word in self.generate(prompt, max_new_tokens).split():
            time.sleep(0.005)
            yield word + " "


class HFBackend:
    """The real thing. pip install torch transformers accelerate first,
    and honestly a GPU for anything above ~3B.

    Loads lazily on the first generate call — so importing app.py with
    backend: hf stays cheap until the model is actually needed.

    quantization: "none" (default) or "8bit". 8-bit loads the weights
    as int8 via bitsandbytes (works on CPU too, dequantizes on the fly
    at each matmul). Set in config.yaml; falls back to "none" with a
    warning if the 8-bit load fails for any reason.
    """

    # vram maths for Qwen2-0.5B-Instruct, worked out before loading:
    #   weights:    494M params x 2 B (fp16)            ~ 1.0 GB
    #   kv cache:   2 x 24 layers x 896 dim x 2 B       ~ 86 KB per token
    #               (2k-ctx worst case -> ~170 MB, usually way less)
    #   torch + activations overhead                    ~ 300 MB
    #   peak total                                      ~ 1.5 GB
    # so ~2 GB of free VRAM (or RAM on CPU) is the honest minimum.
    # on CPU the same maths applies in RAM, just ~10x slower per token.
    # with quantization: 8bit the weights halve to ~0.5 GB (CPU int8 path).

    def __init__(self, model_id, dtype="float16", quantization="none"):
        self.model_id = model_id
        self.dtype = dtype
        q = str(quantization or "none").lower()
        self.quantization = q if q in ("none", "8bit") else "none"
        self.torch = None   # set by _ensure_loaded, kept for dtype lookups
        self.tok = None
        self.model = None

    @property
    def loaded(self):
        return self.model is not None

    def _ensure_loaded(self):
        if self.loaded:
            return
        try:
            import torch
        except ImportError as e:
            raise RuntimeError(
                "HF backend needs torch (pip install torch) — or flip "
                "config.yaml back to backend: mock") from e
        try:
            from transformers import AutoTokenizer, AutoModelForCausalLM
        except ImportError as e:
            raise RuntimeError(
                "HF backend needs transformers (pip install transformers "
                "accelerate)") from e
        # fp16 matmuls are a GPU thing — on CPU float32 is faster and safer
        dtype = (torch.float32 if not torch.cuda.is_available()
                 else getattr(torch, self.dtype, torch.float16))
        try:
            tok = AutoTokenizer.from_pretrained(self.model_id)
            if self.quantization == "8bit":
                try:
                    model = self._load_8bit()
                except Exception as e:
                    # 8-bit didn't pan out — warn loudly, serve unquantized
                    print(f"warning: 8-bit quantization failed ({e}); "
                          "falling back to unquantized weights")
                    self.quantization = "none"
                    model = self._load_plain(dtype)
            else:
                model = self._load_plain(dtype)
        except Exception as e:
            raise RuntimeError(
                f"couldn't fetch {self.model_id} from the HF hub "
                f"(check the model id and your network): {e}") from e
        self.torch, self.tok, self.model = torch, tok, model

    def _load_plain(self, dtype):
        from transformers import AutoModelForCausalLM
        return AutoModelForCausalLM.from_pretrained(
            self.model_id, dtype=dtype, device_map="auto")

    def _load_8bit(self):
        # bitsandbytes keeps weights as int8 + an fp scale per row and
        # dequantizes on the fly at each matmul — real halved memory,
        # slight speed cost, works on CPU (no CUDA kernel needed for this)
        from transformers import AutoModelForCausalLM, BitsAndBytesConfig
        return AutoModelForCausalLM.from_pretrained(
            self.model_id,
            quantization_config=BitsAndBytesConfig(load_in_8bit=True),
            device_map="auto")

    @property
    def tokenizer(self):
        # chat template needs the tokenizer even before the first generate
        self._ensure_loaded()
        return self.tok

    def _inputs(self, prompt):
        self._ensure_loaded()
        return self.tok(prompt, return_tensors="pt").to(self.model.device)

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        self._ensure_loaded()
        inputs = self._inputs(prompt)
        out = self.model.generate(**inputs, max_new_tokens=max_new_tokens,
                                  temperature=temperature,
                                  do_sample=temperature > 0)  # greedy when 0
        return self.tok.decode(out[0][inputs.input_ids.shape[1]:],
                               skip_special_tokens=True)

    def stream(self, prompt, max_new_tokens=256):
        from transformers import TextIteratorStreamer
        from threading import Thread
        self._ensure_loaded()
        inputs = self._inputs(prompt)
        streamer = TextIteratorStreamer(self.tok, skip_special_tokens=True,
                                        skip_prompt=True)  # prompt would echo otherwise
        Thread(target=self.model.generate,
               kwargs={**inputs, "max_new_tokens": max_new_tokens,
                       "streamer": streamer}, daemon=True).start()
        yield from streamer


class VLLMBackend:
    """Same generate/stream interface, but served by vLLM — paged
    attention + continuous batching, so much higher tok/s on a GPU.

    Needs: pip install vllm, and a CUDA GPU (vLLM doesn't do CPU).
    Loads lazily on the first generate call. If the vllm package isn't
    importable, __init__ raises and LocalLLM falls back to the HF
    backend with a warning — same model, just slower.
    """

    def __init__(self, model_id, quantization="none"):
        try:
            import vllm  # noqa: F401 — availability probe, real import is lazy
        except ImportError as e:
            raise RuntimeError(
                "vllm backend needs the vllm package "
                "(pip install vllm, CUDA GPU required)") from e
        self.model_id = model_id
        q = str(quantization or "none").lower()
        self.quantization = q if q in ("none", "awq", "gptq") else "none"
        self.llm = None

    @property
    def loaded(self):
        return self.llm is not None

    def _ensure_loaded(self):
        if self.loaded:
            return
        from vllm import LLM
        # vllm grabs ~90% of GPU RAM by default; fine on a dedicated box,
        # lower gpu_memory_utilization if you're sharing it
        self.llm = LLM(
            model=self.model_id,
            quantization=(self.quantization
                          if self.quantization != "none" else None))

    @property
    def tokenizer(self):
        # chat template needs the tokenizer even before the first generate
        self._ensure_loaded()
        return self.llm.get_tokenizer()

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        from vllm import SamplingParams
        self._ensure_loaded()
        params = SamplingParams(max_tokens=max_new_tokens,
                                temperature=temperature)
        return self.llm.generate([prompt], params)[0].outputs[0].text

    def stream(self, prompt, max_new_tokens=256):
        # vllm's offline LLM.generate returns whole outputs — no public
        # streaming iterator — so chunk the finished text like MockBackend;
        # TTFT here ~= full generate latency, not a real first token
        for word in self.generate(prompt, max_new_tokens).split():
            yield word + " "


# ---------------------------------------------------------------- LLM
class LocalLLM:
    def __init__(self, config_path="config.yaml", quantization=None,
                 backend=None):
        self.cfg = yaml.safe_load(open(config_path))
        # explicit kwarg (bench) beats config.yaml
        which = backend or self.cfg.get("backend", "mock")
        if which == "vllm":
            try:
                self.backend = VLLMBackend(
                    self.cfg["model_id"],
                    self.cfg.get("vllm_quantization", "none"))
            except RuntimeError as e:
                # no vllm package on this box — serve the same model
                # through the HF backend instead of refusing to start
                print(f"warning: {e}; falling back to the HF backend")
                self.backend = HFBackend(self.cfg["model_id"],
                                         self.cfg.get("dtype", "float16"))
        elif which == "hf":
            # explicit kwarg (bench) beats config.yaml; default none keeps
            # yesterday's behaviour untouched
            q = (quantization if quantization is not None
                 else self.cfg.get("quantization", "none"))
            self.backend = HFBackend(self.cfg["model_id"],
                                     self.cfg.get("dtype", "float16"),
                                     quantization=q)
        else:
            self.backend = MockBackend()
        # prompts live as versioned files, not inline strings — much easier
        # to diff v1 vs v2 later when something regresses
        self.prompt_dir = self.cfg.get("prompt_dir", "prompts/v1")

    def load_prompt(self, name, **kwargs):
        text = open(f"{self.prompt_dir}/{name}.txt").read()
        return text.format(**kwargs)

    def build_prompt(self, messages):
        # HF and vLLM expose the tokenizer's real chat template; the mock
        # gets the cheap stand-in
        if hasattr(self.backend, "tokenizer"):
            return self.backend.tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True)
        return "\n".join(f"{m['role']}: {m['content']}" for m in messages
                         ) + "\nassistant:"

    def chat(self, messages, max_new_tokens=256, temperature=0.7):
        return self.backend.generate(self.build_prompt(messages),
                                     max_new_tokens, temperature)

    def chat_stream(self, messages, max_new_tokens=256):
        yield from self.backend.stream(self.build_prompt(messages),
                                       max_new_tokens)

    # -- structured output: ask -> check what came back -> show the model
    #    its mistake and try again ----------------------------------------
    @staticmethod
    def _extract_json(text, required):
        # cheap trick: grab the outermost { ... } instead of trusting the
        # model to output *only* JSON (it rarely does on the first try)
        start, end = text.find("{"), text.rfind("}")
        if start == -1:
            return None, "no JSON object found"
        try:
            obj = json.loads(text[start:end + 1])
        except json.JSONDecodeError as e:
            return None, f"invalid JSON: {e}"
        missing = [f for f in required if f not in obj]
        if missing:
            return None, f"missing fields: {missing}"
        return obj, None

    def extract_json(self, prompt, required, retries=2):
        # naming the fields up front helps real models too — vague
        # "give me JSON" prompts come back with the wrong shape
        prompt = (prompt + "\nRespond with ONLY a JSON object with these "
                  "fields: %s." % ", ".join(required))
        for _ in range(retries + 1):
            raw = self.backend.generate(prompt)
            obj, err = self._extract_json(raw, required)
            if obj:
                return obj
            prompt += f"\nYour last output had an error: {err}. Fix it."
        raise ValueError("model failed to produce valid JSON after retries")
