"""LocalLLM: one clean interface over model backends.

  MockBackend — instant, no downloads. Answers are templated; good for
                developing the API, prompts, retries, and benchmarks.
  HFBackend   — real Hugging Face model (needs torch + transformers +
                a GPU for anything above ~3B).

# SWAP: config.yaml backend: mock -> hf
"""
import json
import time
import re

import yaml


# ---------------------------------------------------------------- backends
class MockBackend:
    """Deterministic stand-in. Not intelligent — exercises everything else."""

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        if "JSON" in prompt:
            return '{"order_id": "ORD-1", "items": 2}'
        return ("This is a mock completion. In production this text would be "
                "generated by the loaded model.")

    def stream(self, prompt, max_new_tokens=256):
        for word in self.generate(prompt, max_new_tokens).split():
            time.sleep(0.005)
            yield word + " "


class HFBackend:
    """Real backend. Needs: pip install torch transformers accelerate."""

    def __init__(self, model_id, dtype="float16"):
        import torch
        from transformers import AutoTokenizer, AutoModelForCausalLM
        self.torch = torch
        self.tok = AutoTokenizer.from_pretrained(model_id)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_id, torch_dtype=getattr(torch, dtype), device_map="auto")

    def _inputs(self, prompt):
        return self.tok(prompt, return_tensors="pt").to(self.model.device)

    def generate(self, prompt, max_new_tokens=256, temperature=0.7):
        inputs = self._inputs(prompt)
        out = self.model.generate(**inputs, max_new_tokens=max_new_tokens,
                                  temperature=temperature, do_sample=True)
        return self.tok.decode(out[0][inputs.input_ids.shape[1]:],
                               skip_special_tokens=True)

    def stream(self, prompt, max_new_tokens=256):
        from transformers import TextIteratorStreamer
        from threading import Thread
        inputs = self._inputs(prompt)
        streamer = TextIteratorStreamer(self.tok, skip_special_tokens=True)
        Thread(target=self.model.generate,
               kwargs={**inputs, "max_new_tokens": max_new_tokens,
                       "streamer": streamer}, daemon=True).start()
        yield from streamer


# ---------------------------------------------------------------- LLM
class LocalLLM:
    def __init__(self, config_path="config.yaml"):
        self.cfg = yaml.safe_load(open(config_path))
        if self.cfg.get("backend", "mock") == "hf":
            self.backend = HFBackend(self.cfg["model_id"],
                                     self.cfg.get("dtype", "float16"))
        else:
            self.backend = MockBackend()
        # prompt templates are versioned FILES, not inline strings
        self.prompt_dir = self.cfg.get("prompt_dir", "prompts/v1")

    def load_prompt(self, name, **kwargs):
        text = open(f"{self.prompt_dir}/{name}.txt").read()
        return text.format(**kwargs)

    def build_prompt(self, messages):
        # mock template; HFBackend path uses tok.apply_chat_template instead
        if isinstance(self.backend, HFBackend):
            return self.backend.tok.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True)
        return "\n".join(f"{m['role']}: {m['content']}" for m in messages
                         ) + "\nassistant:"

    def chat(self, messages, max_new_tokens=256, temperature=0.7):
        return self.backend.generate(self.build_prompt(messages),
                                     max_new_tokens, temperature)

    def chat_stream(self, messages, max_new_tokens=256):
        yield from self.backend.stream(self.build_prompt(messages),
                                       max_new_tokens)

    # -- structured output: generate -> validate -> feed error back --------
    @staticmethod
    def _extract_json(text, required):
        start, end = text.find("{"), text.rfind("}")
        if start == -1:
            return None, "no JSON object found"
        try:
            obj = json.loads(text[start:end + 1])
        except json.JSONDecodeError as e:
            return None, f"invalid JSON: {e}"
        missing = [f for f in required if f not in obj]
        if missing:
            return None, f"missing fields: {missing}"
        return obj, None

    def extract_json(self, prompt, required, retries=2):
        prompt = prompt + "\nRespond with ONLY a JSON object."
        for _ in range(retries + 1):
            raw = self.backend.generate(prompt)
            obj, err = self._extract_json(raw, required)
            if obj:
                return obj
            prompt += f"\nYour last output had an error: {err}. Fix it."
        raise ValueError("model failed to produce valid JSON after retries")
